// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhQJEcmjlHl2ANNq9UHOkI6TZKOEWiSdA',
    appId: '1:168536371628:web:5ecf9ad88a239d4a780a09',
    messagingSenderId: '168536371628',
    projectId: 'socialmedia-b069a',
    authDomain: 'socialmedia-b069a.firebaseapp.com',
    storageBucket: 'socialmedia-b069a.firebasestorage.app',
    measurementId: 'G-L1QEJ3VP1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJdCR1HzRH_qaZxmBkN1rWod2BhzeJiCE',
    appId: '1:168536371628:android:f1570f27dd07331b780a09',
    messagingSenderId: '168536371628',
    projectId: 'socialmedia-b069a',
    storageBucket: 'socialmedia-b069a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBShvfk5m7GHtxejYRoozXv9lhGryfX1Tk',
    appId: '1:168536371628:ios:7ed6f8c1251c4bef780a09',
    messagingSenderId: '168536371628',
    projectId: 'socialmedia-b069a',
    storageBucket: 'socialmedia-b069a.firebasestorage.app',
    iosBundleId: 'com.example.socialmediaf',
  );
}
